version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks-local
    expose:
      - 5432
    ports:
      - 5432:5432
